local basic = require("basicMain")
local bufferline = require("bufferlineMain")
local explorer = require("explorerMain")
local colorscheme = require("colorschemeMain")
local fuzzyfinder = require("fuzzyfinderMain")
local treesitter = require("treesitterMain")
print("hello")
basic.setKeys()
basic.runSetup()
bufferline.setKeys()
bufferline.runSetup()
print("helloExplorer")
explorer.runSetup()
explorer.setKeys()
colorscheme.runSetup()
fuzzyfinder.setKeys()
treesitter.runSetup()
