local basic = require("basicMain")
local bufferline = require("bufferlineMain")
local explorer = require("explorerMain")
local colorscheme = require("colorschemeMain")
local fuzzyfinder = require("fuzzyfinderMain")
local treesitter = require("treesitterMain")

basic.setKeys()
basic.runSetup()
print ("Basic setup")
bufferline.setKeys()
bufferline.runSetup()
print ("Bufferline setup")
explorer.runSetup()
explorer.setKeys()
print ("Explorer setup")
colorscheme.runSetup()
print ("Colorscheme setup")
fuzzyfinder.setKeys()
print ("Fuzzyfinder setup")
treesitter.runSetup()
print ("Treesitter setup")
